/**
 * 
 */

// main process as backend. 
const path = require('path');
const { app, BrowserWindow, Menu, ipcMain, ipcRenderer } = require('electron');
const fs = require('fs');
const { shell } = require('electron') // deconstructing assignment


const isDev = process.env.NODE_ENV !== 'development';
const isMac = process.platform === 'darwin'; // win32, linux
let mainWindow;
let statsWindow;

let pathClientFolder = "C:/Users/yahir/Dropbox/WIA/Public/WIA L&I Intakes/TERI'S L&I CLIENTS"; // default path to client folder
let data;   // holds array of client data objects. generated by getClientData function


/**
 * create stats window not currently being used but this is how you'd do it.
 */
function createStatsWindow() {
    statsWindow = new BrowserWindow({
        title: "client stats",
        width: isDev ? 1000 : 600,
        height: 600,
        webPreferences: {
            contextIsolation: false,
            nodeIntegration: true
        },
        frame: false,
        autoHideMenuBar: true,
        icon: "renderer/images/icons/icon.png"
    });

    statsWindow.loadFile(path.join(__dirname, './renderer/stats.html'));
}

/**
 * create the main window
 */
function createMainWindow() {
    mainWindow = new BrowserWindow({
        title: "frameless app",
        width: isDev ? 1000 : 600,
        height: 600,
        webPreferences: {
            contextIsolation: true,
            nodeIntegration: true,
            preload: path.join(__dirname, 'preload.js')
        },
        frame: false,
        autoHideMenuBar: true,
        icon: "renderer/images/icons/icon.png"
    });

    // open dev tools if in dev env
    if (isDev) {
        mainWindow.webContents.openDevTools();
    }

    mainWindow.loadFile(path.join(__dirname, './renderer/html/index.html'));
}

/**
 * create the main window when able to
 */
app.whenReady().then(() => {
    createMainWindow();

    if (BrowserWindow.getAllWindows().length === 0) {
        createMainWindow();
    }
});

/**
 * quite the app when all windows are closed
 */
app.on('window-all-closed', () => {
    if (!isMac) {
        app.quit();
    }
});

/**
 * load files/index html into main window
 */
ipcMain.on('load-files-window', (events, args) => {
    // this opens a new window
    // createStatsWindow;

    // this loads the current window with disired .html file (index.html)
    mainWindow.loadFile(path.join(__dirname, './renderer/html/index.html'));
});

/**
 * load stats html into main window
 */
ipcMain.on('load-stats-window', () => {
    // this opens a new window
    // createStatsWindow;

    // this loads the current window with disired .html file (stats.html)
    mainWindow.loadFile(path.join(__dirname, './renderer/html/stats.html'));
});

/**
 * load settings html into main window
 */
ipcMain.on('load-settings-window', () => {
    // this opens a new window
    // createStatsWindow;

    /// this loads the current window with disired .html file (settings.html)
    mainWindow.loadFile(path.join(__dirname, './renderer/html/settings.html'));
});

/**
 * reload the mainWindow
 */
ipcMain.on('reload-window', () => {
    // app.relaunch();
    mainWindow.webContents.reloadIgnoringCache()
});
/**
 * minimize the main window
 */
ipcMain.on('minimize-window', () => {
    mainWindow.minimize()
});
/**
 * close the application
 */
ipcMain.on('close-window', () => {
    app.quit();
});


/**
 * receive the path to client folder from a front end
 * js file and set it to the global pathClientFolder variable
 */
ipcMain.on('send-path', (events, data) => {
    pathClientFolder = data;
});

/**
 * send the path to client folder (pathClientFolder vairable) 
 * to front end js file requesting it
 */
ipcMain.handle('get-path', () => pathClientFolder)

/**
 * send the data gathered fromt he getClientData() function
 * to the front end js file requesting it
 */
ipcMain.handle('get-data', () => getClientData())

/**
 * receive request to open client sitch
 * 
 * @param events    type of event
 * @param data      array with two paths
 *                  [0] is the path to sitch if unable to open
 *                  will attemp to open [1] path to client folder
 */
ipcMain.on('open-sitch', (events, data) => {
      if (fs.existsSync(data[0])) {
        shell.openPath(data[0], { activate: true })
    } else {
        shell.openExternal(data[1], { activate: true })
    }
    
});

/**
 * receive request to open client folder
 * 
 * @param events    type of event
 * @param data      array with two paths
 *                  [0] is the path to specific client claim folder
 *                  if unable to open will open [1] path to client folder
 */
ipcMain.on('open-folder', (events, data) => {
    try {
        shell.openExternal(data[0], { active: true });
    }
    catch (err) {
        console.log("error: unable to locate", data[0], "opening", data[1])
        shell.openExternal(data[1], { active: true });
    }
   
});

/**
 * function that collects and creates object that contains client data
 * search through clients folder for names and then searches for client-data.json
 * within client folder to obtain data
 * 
 * @returns {object}    consists of id, name, phone, dob, claim numbers, dois, rep 
 */
function getClientData() {
    let data = [];
    let idNum = 0;
    let folders;
    let validClientFolder;
    try {
        folders = fs.readdirSync(pathClientFolder);
    } catch(err) {
        console.log("unable to read folders")
 
    }

    try {
    folders.forEach(folder => {
        // return if not a directory and non client folder
        let isDir = fs.lstatSync(pathClientFolder + '/' + folder).isDirectory()
        if (!isDir || folder.includes('#')) {
            return;
        }

        // create json object from json file in client folder
        let fileJSON = pathClientFolder + '/' + folder + '/client-data.json';
        let clientData;
        let jsonObj;

        // try to access client.json and create jsonObj
        try {
            clientData = fs.readFileSync(fileJSON);
            let json = JSON.parse(clientData);
            data.push({
                // sometimes you need json[0] other times you don't... weird.
                "id": idNum,
                "name": json[0].name,
                "dob": json[0].dob,
                "phone": json[0].phone,
                "claims": json[0].claims,
                "rep": json[0].rep
            })
        }
        catch (err) {
            console.log("error", folder, " missing json.");
            // basic data absent json file
            data.push({
                "id": idNum,
                "name": folder,
                "dob": "",
                "phone": "",
                "claims": [""],
                "rep": ""
            })
        }
        idNum++;
    })
    
}
catch(err) {
    console.log('no clients found in folder')
}
return data;
}